---
abstract: 'Extension for LWP to allow parallel HTTP and FTP access'
author:
  - 'Marc Langheinrich <marclang@cpan.org>'
  - 'Mike South (maintainer) <msouth@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ParallelUserAgent
no_index:
  directory:
    - t
    - inc
requires:
  IO::Socket::SSL: 0
  LWP: 5.64
  LWP::Protocol::http10: 0
  LWP::Protocol::https10: 0
version: 2.60
